config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'main#index'

      get 'main/index'
      resources :teachers, except: :show
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/main_controller.rb
class Admin::MainController < Admin::BaseController

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/teachers_controller.rb
class Admin::TeachersController < Admin::BaseController
def index
  @teachers - Teacher.order(id: :desk)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/main/index.html.slim
h1 Admin::Main#index
p Find me in app/views/admin/main/index.html.slim

app/views/admin/shared/_main.menu.html.slim
av.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Brand
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#"
            | Link
            span.sr-only (current)
        li
          a href="#"  Link
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Dropdown
            span.caret
          ul.dropdown-menu
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider role="separator"
            li
              a href="#"  Separated link
            li.divider role="separator"
            li
              a href="#"  One more separated link
      form.navbar-form.navbar-left
        .form-group
          input.form-control placeholder="Search" type="text" /
        button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        li
          a href="#"  Link
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Dropdown
            span.caret
          ul.dropdown-menu
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider role="separator"
            li
              a href="#"  Separated link
                /! /.navbar-collapse
                /! /.container-fluid

app/views/admin/shared/_main_menu.html.slim
av.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "OnSchool", admin_root_path, class: 'navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#"
            | Link
            span.sr-only (current)
        li
          a href="#"  Link
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Dropdown
            span.caret
          ul.dropdown-menu
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider role="separator"
            li
              a href="#"  Separated link
                /! /.navbar-collapse
                /! /.container-fluid

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SApp
    = csrf_meta_tags
    = stylesheet_link_tag 'admin', media: 'all'
    = javascript_include_tag 'admin'
  body
    = render 'admin/shared/main_menu'
    .container
      .row
        .col-md-12
         = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SApp</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teachers/_teacher.html.slim
tr
  td= teacher.first_name
  td= teacher.last_name
  td= teacher.description

app/views/teachers/create.html.slim
h1 Teachers#create
p Find me in app/views/teachers/create.html.slim

app/views/teachers/destroy.html.slim
h1 Teachers#destroy
p Find me in app/views/teachers/destroy.html.slim

app/views/teachers/edit.html.slim
h1 Teachers#edit
p Find me in app/views/teachers/edit.html.slim

app/views/teachers/index.html.slim
h3 Преподаватели

table.table.table-striped
  thead
    tr
      th Имя
      th Фамилия
      th Описание
   tbody
     = render @teachers

app/views/teachers/new.html.slim
h1 Teachers#new
p Find me in app/views/teachers/new.html.slim

app/views/teachers/update.html.slim
h1 Teachers#update
p Find me in app/views/teachers/update.html.slim